### ISSUE TITLE
[Question] Does this inlcude the ER diagram editor ?

### ISSUE THREAD

**Issue by Xsmael** [mleandrojr/mysql-workbench-dark-theme#1]
Hi! 
Will the theme also apply to the ER diagram editor ?

**Comment by mleandrojr** [comment]
It does not affect the ER diagram editor.
Maybe it uses another file to this application area, but I can't find this file yet.

**Comment by Xsmael** [comment]
oh nooo!!  :(  :'(

Alright if you find its somehow let us know; I'll also report back here if I find it.
