### ISSUE TITLE
Can't apply 

### ISSUE THREAD

**Issue by yigitsr** [mleandrojr/mysql-workbench-dark-theme#6]
I can't make MySQL dark theme with this code_editor.xml. I tried and applied 2 other themes but I didn't like them. I liked this theme's color but I'm not able to change the theme. What could be the problem? After appyling this theme, all I got is white background and black fore colors.
"I'm using MySQL 6.3"

**Comment by mleandrojr** [comment]
I think it's not working anymore since the last MySQL Workbench updates.
I'm trying to understand the new scintilla rules to try to apply this theme on a new code_editor.xml version.

**Comment by yigitsr** [comment]
Thank you for the reply.
